name: Bug Report
description: Report a bug in vulkan-tutorials
labels: [bug]
assignees: [brobeson]
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of vulkan-tutorials are you using?
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the current erroneous behavior.
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: What should happen?
      description: Describe the expected behavior.
    validations:
      required: true
